# Generated by Django 5.2.1 on 2025-05-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_api_app', '0002_coursemajormodel_gendermodel_passwordresetmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMajorModel',
        ),
        migrations.DeleteModel(
            name='GenderModel',
        ),
        migrations.DeleteModel(
            name='PasswordResetModel',
        ),
    ]
